site_name: Evelina_IS
theme:
    name: material
    highlightjs: true
    hljs_languages:
        - c
        - assembly
        - python
    primary: purple
    icon:
        logo: material/dog
    language: en
    features:
        - navigation.tabs
        - search.highlight
        - search.suggestions

copyright: "Copyright © 2026 Evelina_IS"

nav:
    - 首页: index.md
    - fds_project:
        - project1: fds_project/project1.md

# Markdown 扩展
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - attr_list
    - def_list
    - footnotes
    - tables
    - toc:
        permalink: true
    # 数学公式支持
    - pymdownx.arithmatex:
        generic: true

# 插件
plugins:
    - search

# 添加 MathJax JavaScript
extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js